on:
  pull_request:
    types: [opened]
name: Pull Requests
jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    steps:
      - name: '读取仓库内容'
        uses: actions/checkout@main
      - name: '拉取请求校验'
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
