on:
  workflow_dispatch:
  schedule:
    # run every 12 hours
    - cron: '20 */12 * * *'
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - name: '读取仓库内容'
        uses: actions/checkout@v4
      - name: '更新仓库'
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: '1'
